import math
from BioInfoToolkit.Sequences.Profiling import findProfileMostProbableKmers
from BioInfoToolkit.IO import readTextFile, result_path_from_input_path, solution_path_from_input_path, writeTextFile
import os

"""
https://rosalind.info/problems/ba2c/

Given a profile matrix Profile, we can evaluate the probability of every k-mer in a string Text and find a Profile-most probable k-mer in Text, i.e., a k-mer that was most likely to have been generated by Profile among all k-mers in Text. For example, ACGGGGATTACC is the Profile-most probable 12-mer in GGTACGGGGATTACCT. Indeed, every other 12-mer in this string has probability 0.

In general, if there are multiple Profile-most probable k-mers in Text, then we select the first such k-mer occurring in Text.

Profile-most Probable k-mer Problem
    Find a Profile-most probable k-mer in a string.

    Given: A string Text, an integer k, and a 4 x k matrix Profile.

    Return: A Profile-most probable k-mer in Text. (If multiple answers exist, you may return any one.)
"""

OutputT = str


def verify(result: OutputT, solution: OutputT, text: str, k: int, profile_mat: list[list[float]]) -> bool:
    alphabet = sorted(['A', 'C', 'G', 'T'])
    alphabet_map = {symb: i for i, symb in enumerate(alphabet)}
    prob_res = math.prod(profile_mat[alphabet_map[symb]][i]
                                for i, symb in enumerate(result))
    prob_sol = math.prod(profile_mat[alphabet_map[symb]][i]
                         for i, symb in enumerate(solution))

    correct = len(result) == k and text.find(result) != -1 and prob_res == prob_sol
    return correct


def solve(sequence: str, k: int, profile_mat: list[list[float]], alphabet: list[str]) -> OutputT:
    kmers, _ = findProfileMostProbableKmers(
        sequence, k, profile_mat, alphabet)
    return kmers[0]


def load_results(path: str) -> OutputT:
    lines = readTextFile(path)
    median_string = lines[0]
    return median_string


def solve_and_check(input_path: str) -> bool:
    solution_path = solution_path_from_input_path(input_path)

    lines = readTextFile(input_path)
    sequence = lines[0]
    k = int(lines[1])

    alphabet = ['A', 'C', 'G', 'T']
    l = len(alphabet)
    profile_mat = [[float(k) for k in line.split()] for line in lines[2:2+l]]

    result = solve(sequence, k, profile_mat, alphabet)

    solution = load_results(solution_path)

    correct = verify(result, solution, sequence, k, profile_mat)
    return correct


if __name__ == "__main__":
    cwd = os.path.realpath(os.path.dirname(__file__))
    path = f'{cwd}/rosalind_ba2c_1.txt'

    lines = readTextFile(path)
    sequence = lines[0]
    k = int(lines[1])

    alphabet = sorted(['A', 'C', 'G', 'T'])
    l = len(alphabet)
    profile_mat = [[float(k) for k in line.split()] for line in lines[2:2+l]]

    kmer = solve(sequence, k, profile_mat, alphabet)

    out = kmer
    print(out)

    result_path = result_path_from_input_path(path)
    writeTextFile(result_path, out, 'w')

    correct = solve_and_check(path)
    print(correct)

